### ISSUE TITLE
Error when reloading plugins

### ISSUE THREAD

**Issue by CyrilleB79** [tsengwoody/Access8Math#101]
### Steps to reproduce
1. Use a brand new NVDA installation (e.g. portable)
2. Install Access8Math and restart
3. Look in NVDA menu or settings dialog to check that NVDA has loaded A8M
4. Reload the plugins with `NVDA+control+f3`
5. Look again in NVDA menu or settings dialog to check if NVDA has loaded A8M

### Actual result

At step 4, the following error is logged:

```
ERROR - globalPluginHandler.listPlugins (10:13:23.152) - MainThread (3744):
Error importing global plugin Access8Math
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 23, in listPlugins
  File "importlib\__init__.pyc", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Cyrille\Documents\DevP\TestA8M\userConfig\addons\Access8Math\globalPlugins\Access8Math\__init__.py", line 99, in <module>
    from .command.context import A8MFEVContextMenuView
  File "C:\Users\Cyrille\Documents\DevP\TestA8M\userConfig\addons\Access8Math\globalPlugins\Access8Math\command\context.py", line 12, in <module>
    from ..lib.viewHTML import Access8MathDocument
  File "C:\Users\Cyrille\Documents\DevP\TestA8M\userConfig\addons\Access8Math\globalPlugins\Access8Math\lib\viewHTML.py", line 26, in <module>
    import xml.etree.ElementTree as etree
ImportError: cannot import name 'etree' from 'xml' (C:\Users\Cyrille\Documents\DevP\TestA8M\userConfig\addons\Access8Math\globalPlugins\Access8Math\python\xml\__init__.py)
```

At step 5, we can see that the add-on has not been reloaded.

### Expected result
No error and the add-on can be reloaded.

**Comment by tsengwoody** [comment]
Finished commit cfde498
