### ISSUE TITLE
Cannot open localization windows

### ISSUE THREAD

**Issue by CyrilleB79** [tsengwoody/Access8Math#63]
Hi

Found while checking translations of A8M 3.3

### STR
Try to open any of theunicode dic or math rules items in the localization submenu.

### Actual result

The dialog does not open and the following error is in the log:

ERROR - unhandled exception (16:21:00.712) - MainThread (652):
Traceback (most recent call last):
  File "C:\Users\Cyrille\AppData\Roaming\nvda\addons\Access8Math\globalPlugins\Access8Math\__init__.py", line 356, in onSpeechUnicodeDictionary
    language=config.conf["Access8Math"]["settings"]["language"], category='speech'
  File "gui\__init__.pyc", line 162, in _popupSettingsDialog
  File "C:\Users\Cyrille\AppData\Roaming\nvda\addons\Access8Math\globalPlugins\Access8Math\dialogs.py", line 455, in __init__
    symbol = A8M_PM.load_unicode_dic(language=self.language, category=category)
  File "C:\Users\Cyrille\AppData\Roaming\nvda\addons\Access8Math\globalPlugins\Access8Math\A8M_PM.py", line 1427, in load_unicode_dic
    with io.open(frp, 'r', encoding='utf-8') as fr, io.open(frp_user, 'w', encoding='utf-8') as fr_user:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Cyrille\\AppData\\Roaming\\nvda\\addons\\Access8Math\\globalPlugins\\Access8Math\\locale\\speech\\fr_FR\\unicode.dic'

### Expected result
The dialog opens without error

### Note
The name of the folder found in Windows Explorer is 'fr', not 'fr_FR', hence A8M does not find the file.

**Comment by tsengwoody** [comment]
I fixed it. This issue is caused by A8M initialization language set according to the system language.
Please test again.
