### ISSUE TITLE
Are A8M settings using profiles?

### ISSUE THREAD

**Issue by CyrilleB79** [tsengwoody/Access8Math#75]
It is unclear if A8M settings are meant to be set by profile.

### Steps to reproduce
1. Create a profile for Notepad
2. While in notepad, open the rule settings panel
3. In this window check or uncheck an option, e.g. uncheck "Simplified superscript and subscripts" option
4. Validate
5. Change application, e.g. go in Windows Explorer, so that the default profile is active
6. Open the rules settings panel

### Actual behaviour
* At step 2. and 6. we can see in the Window title that there is no mention of profile/default config. This let us think that A8M does not use profiles.
* At step 6. we can see that the option that was unchecked at step 3 is still checked.
### Expected behaviour
Clarify if A8M should use profile for its settings or not.
* If it should use profiles, indicate the profile's name in the A8M settings window, as done for NVDA multi-category settings window
* If it should not, fix the issue demonstrated with the "steps to reproduce" in this issue.

### A8M version
3.4
### NVDA version
2022.4beta3

**Comment by tsengwoody** [comment]
The result of my test shows that configuration options other than "reading" -> "language" will change with different profiles in Access8Math version 3.5 using NVDA 2023.1. Do you still have this issue? I am willing to try and make changes if it does not require too much effort. However, I believe this feature may not be that important for Access8Math.

**Comment by CyrilleB79** [comment]
I agree that profiles are not so useful for A8M.

The easiest way is to keep them anyway since it is managed automatically.

So that it is clarified, I would just expect that the profile name be indicated in the A8M settings windows impacted by profiles, as it is the case looking at the title of NVDA settings window.

**Comment by tsengwoody** [comment]
OK, I will try to add a feature that indicates the profile name in the A8M settings window affected by profiles.

**Comment by CyrilleB79** [comment]
> OK, I will try to add a feature that indicates the profile name in the A8M settings window affected by profiles.

You could probably copy NVDA's code for what is done in the settings window where the title indicates the profile being used.

However I cannot try anymore since I am facing another issue when trying to open the A8M settings (from the menu):
```
ERROR - unhandled exception (23:28:23.297) - MainThread (20724):
Traceback (most recent call last):
  File "wx\core.pyc", line 3407, in <lambda>
  File "gui\blockAction.pyc", line 65, in funcWrapper
  File "gui\__init__.pyc", line 165, in _popupSettingsDialog
  File "C:\Users\Cyrille\AppData\Roaming\nvda\addons\Access8Math\globalPlugins\Access8Math\dialogs.py", line 400, in __init__
    super().__init__(parent, initialCategory)
  File "gui\settingsDialogs.pyc", line 471, in __init__
  File "gui\settingsDialogs.pyc", line 201, in __init__
  File "gui\settingsDialogs.pyc", line 540, in makeSettings
  File "gui\settingsDialogs.pyc", line 649, in _doCategoryChange
  File "gui\settingsDialogs.pyc", line 577, in _getCategoryPanel
  File "gui\settingsDialogs.pyc", line 335, in __init__
  File "gui\settingsDialogs.pyc", line 345, in _buildGui
  File "C:\Users\Cyrille\AppData\Roaming\nvda\addons\Access8Math\globalPlugins\Access8Math\dialogs.py", line 162, in makeSettings
    available_languages_dict = {k: map[k] for k in available_languages}
  File "C:\Users\Cyrille\AppData\Roaming\nvda\addons\Access8Math\globalPlugins\Access8Math\dialogs.py", line 162, in <dictcomp>
    available_languages_dict = {k: map[k] for k in available_languages}
KeyError: 'fr_FR'
```

Any idea?

**Comment by tsengwoody** [comment]
> Any idea?
Sure, I have found the reason and it can be fixed.

**Comment by tsengwoody** [comment]
Resolving this issue by commit 76dbab.
