### ISSUE TITLE
Unable to update Access8Math with add-on Updater

### ISSUE THREAD

**Issue by CyrilleB79** [tsengwoody/Access8Math#82]
When trying to update A8M via Add-on Updater, I get an error message saying "Error while downloading Access8Math" (or similar).

The log contains the following debug message related to this error:
```
DEBUG - external:globalPlugins.addonUpdater.addonGuiEx.downloadAndInstallAddonUpdates (14:12:47.804) - Thread-18 (18496):
nvda3208: failed to download Access8Math
Traceback (most recent call last):
  File "C:\Users\Cyrille\AppData\Roaming\nvda\addons\addonUpdater\globalPlugins\addonUpdater\addonGuiEx.py", line 236, in downloadAndInstallAddonUpdates
    download.result()
  File "concurrent\futures\_base.pyc", line 428, in result
  File "concurrent\futures\_base.pyc", line 384, in __get_result
  File "concurrent\futures\thread.pyc", line 57, in run
  File "C:\Users\Cyrille\AppData\Roaming\nvda\addons\addonUpdater\globalPlugins\addonUpdater\addonUpdateProc.py", line 191, in downloadAddonUpdate
    raise RuntimeError("Content has incorrect file hash")
RuntimeError: Content has incorrect file hash

```

Maybe you have modified the existing release, hence changing the hash?

**Comment by tsengwoody** [comment]
Oh, I changed the file but didn't update the version. Now I have updated the version to 3.6.2.
Is your updater working now?

**Comment by CyrilleB79** [comment]
Update successful. Thanks!
