### ISSUE TITLE
Failed to import etree

### ISSUE THREAD

**Issue by fcnjd** [tsengwoody/Access8Math#98]
Hello,
thank you for all your work in this!
I'd like to send a bug report preventing the plugin from getting loaded: I use NVDA 2024.1 and Access8math 4.0. Below is the stacktrace. Since I already tried rebooting my system and restarting NVDA manually, I think this error isn't only on my side.
Cheers, Julian
Error importing global plugin Access8Math
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 23, in listPlugins
  File "importlib\__init__.pyc", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Fabian\AppData\Roaming\nvda\addons\Access8Math\globalPlugins\Access8Math\__init__.py", line 98, in <module>
    from .command.context import A8MFEVContextMenuView
  File "C:\Users\Fabian\AppData\Roaming\nvda\addons\Access8Math\globalPlugins\Access8Math\command\context.py", line 11, in <module>
    from ..editor import EditorFrame
  File "C:\Users\Fabian\AppData\Roaming\nvda\addons\Access8Math\globalPlugins\Access8Math\editor.py", line 9, in <module>
    from lib.viewHTML import Access8MathDocument
  File "C:\Users\Fabian\AppData\Roaming\nvda\addons\Access8Math\globalPlugins\Access8Math\lib\viewHTML.py", line 24, in <module>
    import html5lib
  File "C:\Users\Fabian\AppData\Roaming\nvda\addons\Access8Math\globalPlugins\Access8Math\package\html5lib\__init__.py", line 25, in <module>
    from .html5parser import HTMLParser, parse, parseFragment
  File "C:\Users\Fabian\AppData\Roaming\nvda\addons\Access8Math\globalPlugins\Access8Math\package\html5lib\html5parser.py", line 6, in <module>
    from . import _inputstream
  File "C:\Users\Fabian\AppData\Roaming\nvda\addons\Access8Math\globalPlugins\Access8Math\package\html5lib\_inputstream.py", line 14, in <module>
    from . import _utils
  File "C:\Users\Fabian\AppData\Roaming\nvda\addons\Access8Math\globalPlugins\Access8Math\package\html5lib\_utils.py", line 13, in <module>
    import xml.etree.ElementTree as default_etree
ImportError: cannot import name 'etree' from 'python.xml' (C:\Users\Fabian\AppData\Roaming\nvda\addons\Access8Math\globalPlugins\Access8Math\python\xml\__init__.py)

**Comment by tsengwoody** [comment]
Have you installed 'AI Content Describer'?
When both the "Access8Math" and "AI Content Describer" addons are running simultaneously, it will raise this issue.
I haven't checked what happened yet, but I will do in the future.

**Comment by fcnjd** [comment]
Yes, indeed I have this addon installed. I deactivated it, na d you're right, the error is gone. Thank you for the hint.

**Comment by tsengwoody** [comment]
finish commit a380e5a

**Comment by CyrilleB79** [comment]
@tsengwoody do you plan to make a release soon with this fix? Thanks.
